### ISSUE TITLE
The aemscan breaks and not going till the end in case of Exception with some url call

### ISSUE THREAD

**Issue by mtstv** [Raz0r/aemscan#14]
The aemscan breaks and not going till the end if an Exception occurred while performing a check for example for such URL
https://<domain>/libs/cq/analytics/components/sitecatalystpage/segments.json.servlet.png?datacenter=https://site%23&company=xxx&username=zzz&secret=yyyy

Exception type: <class 'requests.exceptions.ConnectionError'>
Exception value: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Needs to include "try catch" to continue checking the rest of urls till the end of the list.

**Comment by Raz0r** [comment]
Thank you for PR!
